### ISSUE TITLE
OMOP  Remaining table creation

### ISSUE THREAD

**Issue by SomanathSankaran** [databrickslabs/dbignite#46]
https://ohdsi.github.io/CommonDataModel/cdm60.html

As per this document I could see lot of table  Common Data Model of OMOP.
But DBIgnite provides only conversion for 4 entities as per readme.md
Is there any way to add or extend for other tables.
Is there any roadmap to extract the data for other tables

**Comment by zavoraad** [comment]
Hi @SomanathSankaran, 

The OMOP mappings are patient centric resources and assuming that the FHIR bundles are C-CDA CCD. We'd welcome external contributors to this roadmap, but do not plan to extend it at this time due to the many permutations of FHIR messages including prior auths, claims, various FHIR API calls out of an EHR etc. 

Depending on the use case, the easiest path would be to write out [FHIR resources as tables](https://github.com/databricks-industry-solutions/dbignite-forked?tab=readme-ov-file#sql-on-fhir) and then write SQL to map into the relevant OMOP tables. I believe there are several public FHIR to OMOP mapping documents that can be referenced as generally acceptable.

**Comment by zavoraad** [comment]
Hi @SomanathSankaran, please reach out if you know which data source types of FHIR you are looking to map into OMOP and we can make recommendations on an approach and possible augment the OMOP package here. The existing OMOP sample of 4 tables is for C-CDA data regarding patient centric analysis.
